import {
    HorizontalBox,
} from "std-widgets.slint";


export component HelenyButton inherits Rectangle {
    in property <string> text: "默认文字";
    in property <image> icon: @image-url("");
    in property <brush> btn-color: #9ec8ff;
    
    callback clicked();

    // --- 2. 设置容器属性 ---
    width: 90%;
    background: btn-color;
    border-radius: 12px;
    animate background { duration: 150ms; }

    // --- 3. 交互逻辑 ---
    touch := TouchArea {
        clicked => { root.clicked(); }
    }

    // --- 4. 内部布局 ---
    HorizontalLayout {
        alignment: center;
        spacing: 10px;
        padding: 5px;
        
        Image {
            source: root.icon;
            height: 100%;
            visible: root.icon.width > 0; 
        }

        Text {
            text: root.text;
            font-size: 16px;
            vertical-alignment: center;
        }
    }

    states [
        pressed when touch.pressed: {
            background: #7fb5ff;
            opacity: 0.8;
        }
        hover when touch.has-hover: {
            background: #b2d4ff;
        }
    ]
}
